/**
 * @file Error codes for the application
 * @description This file should be moved to @posmul/shared-types package.
 */
// TODO: 이 상수들을 @posmul/shared-types 패키지로 옮겨야 합니다.
export const ERROR_CODES = {
    AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
    AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
    AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
    USER_INSUFFICIENT_POINTS: "USER_INSUFFICIENT_POINTS",
    GAME_NOT_FOUND: "GAME_NOT_FOUND",
    GAME_ALREADY_ENDED: "GAME_ALREADY_ENDED",
    PREDICTION_DEADLINE_PASSED: "PREDICTION_DEADLINE_PASSED",
    STORE_NOT_FOUND: "STORE_NOT_FOUND",
    STORE_NOT_ACTIVE: "STORE_NOT_ACTIVE",
    NETWORK_ERROR: "NETWORK_ERROR",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    FORBIDDEN: "FORBIDDEN",
    CONFLICT: "CONFLICT",
    BUSINESS_LOGIC_ERROR: "BUSINESS_LOGIC_ERROR",
    EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",
};
